[workspace]
members = [
    "spade/spade",
    "spade/spade-macro",
    "test_crates/test_crate",
    "test_crates/test_swim/test_swim_crate",
    "verilator",
    "verilog/verilog",
    "verilog/verilog-macro",
    "verilog/verilog-macro-builder",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Ethan Uppal"]
edition = "2021"
rust-version = "1.83"
description = ""
readme = "README.md"
license = "LGPL-3.0-only"

[workspace.dependencies]
snafu = "0.8.5"
camino = "1.1.9"
libc = "0.2.169"
libloading = "0.8.6"
syn = { version = "2.0.96", features = ["full"] }
